experiment_name: humob2
logging:
  tracking_uri: "file:./mlruns"

data:
  parquet_file: "humob_all_cities_v2_normalized.parquet"
  base_city: "A"
  finetune_cities: ["B","C","D"]

model:
  n_clusters: 16        # poucos clusters para acelerar o KMeans
  n_users: 100000          # amostra pequena de usuários
  sequence_length: 12   # janelas curtas

training:
  base:
    n_epochs: 1
    learning_rate: 3e-4
    batch_size: 16
    mixed_precision: true
  finetune:
    n_epochs: 1
    learning_rate: 5e-5
    batch_size: 8

hardware:
  device: "cuda"        # cai para "cpu" se não tiver GPU
  pin_memory: true
  num_workers: 0        # IterableDataset: evita duplicar leitura

eval:
  compare: true
  n_samples: 200        # comparação rápida

submission:
  enabled: True

outputs:
  models_path: "outputs/models/"
  submissions_path: "outputs/submissions/"
  plots_path: "outputs/plots/"
